import pandas as pd
import os

def generate_icu_patient_features_csv(cohort_output_name, root_dir="."):
    """
    Generates a single CSV file with ICU patient features (aggregated clinical codes).
    
    Args:
        cohort_output_name (str): The name of your ICU cohort file inside ./data/cohort/ 
                                  (without .csv.gz extension).
    """
    
    # Define ICU Specific Paths based on the mimic-iv-data-pipeline structure
    # ICU features usually have the "_icu" suffix in their filenames
    cohort_path = os.path.join(root_dir, "dataCOPD_icu", "cohort", f"{cohort_output_name}.csv.gz")
    diag_path = os.path.join(root_dir, "dataCOPD_icu", "features", "preproc_diag_icu.csv.gz")
    proc_path = os.path.join(root_dir, "dataCOPD_icu", "features", "preproc_proc_icu.csv.gz")
    med_path = os.path.join(root_dir, "dataCOPD_icu", "features", "preproc_med_icu.csv.gz")
    out_path = os.path.join(root_dir, "dataCOPD_icu", "features", "preproc_out_icu.csv.gz")
    chart_path = os.path.join(root_dir, "dataCOPD_icu", "features", "preproc_chart_icu.csv.gz")
    
    output_filename = os.path.join(root_dir, "patient_features_icu_aggregated.csv")

    # 1. Read Cohort Data (Base)
    print(f"[ READING ICU COHORT ] {cohort_path}")
    if not os.path.exists(cohort_path):
        print(f"Error: Cohort file not found at {cohort_path}")
        return

    cohort = pd.read_csv(cohort_path, compression='gzip')
    
    # ICU cohorts primarily use 'stay_id'. 
    # If the user wants a standard 'hadm_id' column, we ensure it exists.
    if 'stay_id' not in cohort.columns:
        print("Error: ICU cohort must contain stay_id.")
        return
        
    # Required demographics/labels
    required_cols = ['stay_id', 'hadm_id', 'subject_id', 'label', 'Age', 'gender', 'ethnicity']
    available_cols = [c for c in required_cols if c in cohort.columns]
    
    cohort = cohort[available_cols].copy()
    if 'Age' in cohort.columns:
        cohort = cohort.rename(columns={'Age': 'age'})

    # 2. Process Diagnoses (Cond)
    print("[ PROCESSING ICU DIAGNOSES ]")
    if os.path.exists(diag_path):
        diag = pd.read_csv(diag_path, compression='gzip')
        # Use 'new_icd_code' if clinical grouping was performed, else 'icd_code'
        icd_col = 'new_icd_code' if 'new_icd_code' in diag.columns else 'icd_code'
        cond_grp = diag.groupby('stay_id')[icd_col].apply(list).reset_index()
        cond_grp = cond_grp.rename(columns={icd_col: 'Cond'})
        cohort = cohort.merge(cond_grp, on='stay_id', how='left')
    else:
        cohort['Cond'] = None

    # 3. Process Procedures (Proc)
    print("[ PROCESSING ICU PROCEDURES ]")
    if os.path.exists(proc_path):
        proc = pd.read_csv(proc_path, compression='gzip')
        # ICU procedures use itemid
        proc_grp = proc.groupby('stay_id')['itemid'].apply(list).reset_index()
        proc_grp = proc_grp.rename(columns={'itemid': 'Proc'})
        cohort = cohort.merge(proc_grp, on='stay_id', how='left')
    else:
        cohort['Proc'] = None

    # 4. Process Medications (Med)
    print("[ PROCESSING ICU MEDICATIONS ]")
    if os.path.exists(med_path):
        med = pd.read_csv(med_path, compression='gzip')
        med_grp = med.groupby('stay_id')['itemid'].apply(list).reset_index()
        med_grp = med_grp.rename(columns={'itemid': 'Med'})
        cohort = cohort.merge(med_grp, on='stay_id', how='left')
    else:
        cohort['Med'] = None

    # 5. Process ICU-specific events (Output and Chart)
    # Aggregating itemids as lists to maintain a flat file structure
    for name, path, col in [('Output', out_path, 'Out'), ('Chart', chart_path, 'Chart')]:
        print(f"[ PROCESSING ICU {name.upper()} ]")
        if os.path.exists(path):
            df_feat = pd.read_csv(path, compression='gzip')
            grp = df_feat.groupby('stay_id')['itemid'].apply(list).reset_index()
            grp = grp.rename(columns={'itemid': col})
            cohort = cohort.merge(grp, on='stay_id', how='left')
        else:
            cohort[col] = None

    # 6. Finalize: Fill empty records with empty lists []
    print("[ FINALIZING AGGREGATED FILE ]")
    for col in ['Cond', 'Proc', 'Med', 'Out', 'Chart']:
        if col not in cohort.columns:
            cohort[col] = None
        cohort[col] = cohort[col].apply(lambda x: x if isinstance(x, list) else [])

    cohort.to_csv(output_filename, index=False)
    print(f"SUCCESS: Generated {output_filename} with {len(cohort)} ICU stays.")

if __name__ == "__main__":
    # Change this to your actual ICU cohort name generated by Step 1 of the pipeline
    my_icu_cohort = "cohort_icu_readmission_30_J44_J44" 
    generate_icu_patient_features_csv(my_icu_cohort, r'D:/ShriyaMasters/Thesis/MIMIC-IV-Data-Pipeline')